@startuml 
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

' Fixes wrapping of some of the captions
skinparam maxMessageSize 160

System_Boundary(aws, "OS") {
  System_Ext(agents, "Monitoring Agents", "An agent that monitors an application")
}

System_Boundary(log_monitoring, "log-monitoring") {
  Container(gateway, "Gateway", "HTTPS", "Receives events from Monitoring Agents and persists them")
  
  Rel(agents, gateway, "Forwards events to")
  
  Container(event_consumer, "EventConsumer", "Java", "Listens to notifications from the EventProducer and persists the HTTP events in the database")

  ContainerDb(event_queue, "Event Bus", "Event Bus", "Queue used to schedule the persistence of HTTP events")
  ContainerDb(timeseries_db, "Events Database", "InfluxDB", "Database that stores the HTTP events")

  Rel(gateway, event_queue, "Notifies new event needs to be persisted")
  Rel(event_queue, event_consumer, "Pulls new events")
  Rel(event_consumer, timeseries_db, "Stores new events")

  Container(alerts, "AlertManager", "Java", "Keeps track of the total traffic of the HTTP server and alerts when the defined threshold is crossed")
  Container(statistics, "StatisticsManager", "Java", "Aggregates events information and reports statistics")

  Rel(alerts, timeseries_db, "Calculate alert status")
  Rel(statistics, timeseries_db, "Calculate statistics")
}

@enduml